'use client';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { FaHome } from 'react-icons/fa';
import { useEffect } from 'react';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
export const handleCheckboxDarkChange = (e: any) => {
  // const targetDiv = document.getElementById("root");
  const bodyElement = document.body;
  if (bodyElement) {
    if (e.target.checked) {
      bodyElement.classList.add('dark-90');
    } else {
      bodyElement.classList.remove('dark-90');
    }
  }
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    document.body.classList.add('dark-90');
  }, []);
  return (
    <html lang="en">
      <body>
        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
        <div>
          <Link href="/slearning">
            <FaHome />
          </Link>
          <label>
            <input type="checkbox" onChange={handleCheckboxDarkChange} defaultChecked={true} />
            Dark mode
          </label>
        </div>
        {children}
      </body>
    </html>
  );
}
