import { DbConnection } from '../../types';

/**
 * Simulated databases for the Microservice Learning Platform demo.
 * Contents mirror db/init.sql (PostgreSQL, schema us_fwd) and the Redis key
 * patterns actually used by cache-service (RedisCacheService):
 *   users::<coCd>:<usrId>  — user snapshots cached from Kafka user.events
 *   entries::<key>         — generic cache API entries
 *   files::activity        — list of recent S3 activity (RabbitMQ, max 25)
 *   auth::activity         — list of recent logins (Kafka, max 50)
 */

const usersDb: DbConnection = {
  name: 'users-db',
  engine: 'PostgreSQL',
  description: 'user-service + auth-service database (schema us_fwd, MyBatis mappers)',
  schemas: [
    {
      name: 'us_fwd',
      tables: [
        {
          name: 'adm_co',
          comment: 'Company reference table (FK target of adm_usr)',
          columns: [
            { name: 'co_cd', type: 'varchar(20)', pk: true },
            { name: 'co_nm', type: 'varchar(100)' },
            { name: 'cre_dt', type: 'timestamp' },
          ],
          rows: [
            ['DEMO', 'Demo Company', '2026-07-01 09:00:00'],
            ['ACME', 'Acme Corporation', '2026-07-01 09:00:00'],
            ['TECH', 'Tech Solutions Inc.', '2026-07-01 09:00:00'],
          ],
        },
        {
          name: 'adm_usr',
          comment:
            'User table (production-style DDL has 60+ columns — a representative subset is shown). Composite PK (co_cd, usr_id)',
          columns: [
            { name: 'co_cd', type: 'varchar(20)', pk: true, comment: 'FK → adm_co' },
            { name: 'usr_id', type: 'varchar(20)', pk: true },
            { name: 'usr_nm', type: 'varchar(50)' },
            { name: 'full_nm', type: 'varchar(100)' },
            { name: 'usr_eml', type: 'varchar(100)' },
            { name: 'mphn_no', type: 'varchar(100)' },
            { name: 'age', type: 'int2' },
            { name: 'com_usr_sx', type: 'varchar(1)' },
            { name: 'act_flg', type: 'varchar(1)', comment: 'Y = active' },
            { name: 'cnt_cd', type: 'varchar(2)' },
            { name: 'cty_nm', type: 'varchar(100)' },
            { name: 'empe_no', type: 'varchar(20)' },
            { name: 'empe_tp_cd', type: 'varchar(3)', comment: 'FT / CT' },
            { name: 'is_root', type: 'varchar(1)' },
            { name: 'spct', type: 'varchar(500)', comment: 'specialty' },
          ],
          rows: [
            [
              'DEMO',
              'admin',
              'Admin',
              'Administrator',
              'admin@demo.com',
              '010-1111-1111',
              35,
              'M',
              'Y',
              'KR',
              'Seoul',
              'EMP001',
              'FT',
              'Y',
              'System Architecture',
            ],
            [
              'DEMO',
              'john',
              'John',
              'John Doe',
              'john@demo.com',
              '010-2222-2222',
              28,
              'M',
              'Y',
              'KR',
              'Seoul',
              'EMP002',
              'FT',
              'N',
              'Spring Boot, Kafka',
            ],
            [
              'DEMO',
              'jane',
              'Jane',
              'Jane Smith',
              'jane@demo.com',
              '010-3333-3333',
              32,
              'F',
              'Y',
              'US',
              'New York',
              'EMP003',
              'FT',
              'N',
              'React, Node.js, Python',
            ],
            [
              'DEMO',
              'bob',
              'Bob',
              'Bob Wilson',
              'bob@demo.com',
              '010-4444-4444',
              45,
              'M',
              'Y',
              'JP',
              'Tokyo',
              'EMP004',
              'CT',
              'N',
              'Microservices, AWS',
            ],
            [
              'DEMO',
              'alice',
              'Alice',
              'Alice Johnson',
              'alice@demo.com',
              '010-5555-5555',
              26,
              'F',
              'Y',
              'KR',
              'Busan',
              'EMP005',
              'FT',
              'N',
              'Docker, K8s, CI/CD',
            ],
            [
              'DEMO',
              'charlie',
              'Charlie',
              'Charlie Brown',
              'charlie@demo.com',
              '010-6666-6666',
              38,
              'M',
              'Y',
              'KR',
              'Seoul',
              'EMP006',
              'FT',
              'N',
              'OAuth2, JWT, OWASP',
            ],
            [
              'DEMO',
              'diana',
              'Diana',
              'Diana Prince',
              'diana@demo.com',
              '010-7777-7777',
              30,
              'F',
              'Y',
              'US',
              'San Francisco',
              'EMP007',
              'FT',
              'N',
              'Spark, Kafka, Redis',
            ],
            [
              'DEMO',
              'inactive',
              'Inactive',
              'Inactive User',
              'inactive@demo.com',
              '010-9999-9999',
              50,
              'M',
              'N',
              'KR',
              'Seoul',
              'EMP008',
              'FT',
              'N',
              'Project Management',
            ],
            [
              'ACME',
              'manager',
              'Manager',
              'Mike Manager',
              'mike@acme.com',
              '010-8001-0001',
              40,
              'M',
              'Y',
              'US',
              'Chicago',
              'AE001',
              'FT',
              'N',
              null,
            ],
            [
              'ACME',
              'dev01',
              'Developer',
              'Dave Developer',
              'dave@acme.com',
              '010-8001-0002',
              29,
              'M',
              'Y',
              'US',
              'Chicago',
              'AE002',
              'FT',
              'N',
              null,
            ],
            [
              'ACME',
              'qa01',
              'QA',
              'Quinn QA',
              'quinn@acme.com',
              '010-8001-0003',
              33,
              'F',
              'Y',
              'US',
              'Chicago',
              'AE003',
              'CT',
              'N',
              null,
            ],
            [
              'TECH',
              'cto',
              'CTO',
              'Chris Technology',
              'chris@techsol.com',
              '010-9001-0001',
              42,
              'M',
              'Y',
              'KR',
              'Seoul',
              'TE001',
              'FT',
              'N',
              null,
            ],
            [
              'TECH',
              'sre01',
              'SRE',
              'Sam Reliable',
              'sam@techsol.com',
              '010-9001-0002',
              31,
              'M',
              'Y',
              'KR',
              'Seoul',
              'TE002',
              'FT',
              'N',
              null,
            ],
          ],
        },
      ],
    },
  ],
};

const redisCache: DbConnection = {
  name: 'redis-cache',
  engine: 'Redis',
  description:
    'cache-service Redis — user snapshots (from Kafka), file/auth activity (from RabbitMQ/Kafka)',
  schemas: [
    {
      name: 'db0',
      tables: [
        {
          name: 'keys',
          comment:
            'Key patterns from RedisCacheService: users::, entries::, files::activity, auth::activity',
          columns: [
            { name: 'key', type: 'string', pk: true },
            { name: 'type', type: 'type' },
            { name: 'ttl_sec', type: 'int', comment: '-1 = no expiry' },
            { name: 'value', type: 'string' },
          ],
          rows: [
            [
              'users::DEMO:admin',
              'string',
              -1,
              '{"eventType":"USER_UPDATED","coCd":"DEMO","usrId":"admin","fullNm":"Administrator"}',
            ],
            [
              'users::DEMO:john',
              'string',
              -1,
              '{"eventType":"USER_CREATED","coCd":"DEMO","usrId":"john","fullNm":"John Doe"}',
            ],
            [
              'users::ACME:dev01',
              'string',
              -1,
              '{"eventType":"USER_CREATED","coCd":"ACME","usrId":"dev01","fullNm":"Dave Developer"}',
            ],
            ['entries::feature-flags', 'string', 3600, '{"newDashboard":true,"betaSearch":false}'],
            [
              'files::activity',
              'list(25)',
              -1,
              '[{"action":"DOWNLOAD","key":"demo/report.pdf","usrId":"john"}, …]',
            ],
            [
              'auth::activity',
              'list(50)',
              -1,
              '[{"eventType":"LOGIN_SUCCESS","usrId":"admin","coCd":"DEMO"}, …]',
            ],
          ],
        },
      ],
    },
  ],
};

export const MS_LEARNING_DATABASES: DbConnection[] = [usersDb, redisCache];
